apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: nginx
  name: nginx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - name: nginx
          image: erixrivas/nginx-avatares:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: API_HOST
              valueFrom:
                secretKeyRef:
                  name: nginx-secrets-dev # Referencia al Secret de dev
                  key: API_HOST

            - name: WEB_HOST
              valueFrom:
                secretKeyRef:
                  name: nginx-secrets-dev # Referencia al Secret de dev
                  key: WEB_HOST

      restartPolicy: Always
