# Usa la imagen base oficial de OpenResty
FROM openresty/openresty:bullseye

# Copia tu archivo nginx.conf al contenedor
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf

# Expone el puerto 80 para el tráfico HTTP
EXPOSE 80

# Comando por defecto para iniciar NGINX
CMD ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]
