apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: api
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - name: api
          image: leopoldox3/api-avatares:v1
          imagePullPolicy: Always
          env:
            - name: FLASK_APP
              value: app.py
            - name: FLASK_ENV
              value: development
            - name: FLASK_RUN_HOST
              value: 0.0.0.0
            - name: FLASK_RUN_PORT
              value: "5000"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
        # imagePullSecrets:
        #   - name: my-registry-secret
        - name: prometheus-exporter
          image: prom/statsd-exporter:v0.28.0
          ports:
            - containerPort: 9102
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
      restartPolicy: Always
