apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort
  selector:
    io.kompose.service: api
  ports:
    - name: api-port
      port: 5000 # Puerto lógico del servicio
      targetPort: 5000 # Puerto del contenedor
      nodePort: 32016 # Puerto expuesto al exterior
    - name: api-metrics
      port: 9102 # Puerto lógico del servicio para métricas
      targetPort: 9102 # Puerto del sidecar container
      nodePort: 32017 # Puerto expuesto al exterior para métricas
