apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["127.0.0.1:9090"]

      - job_name: "api"
        static_configs:
          - targets: ["api.dev.local:5000"]
        metrics_path: /metrics

      - job_name: "web"
        static_configs:
          - targets: ["web:9100"]
        metrics_path: /metrics
