# Usa una imagen base de Python
FROM python:3.10-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

ENV FLASK_APP app.py
ENV FLASK_ENV development
ENV FLASK_RUN_PORT 5000
ENV FLASK_RUN_HOST 0.0.0.0

# Copia los archivos del proyecto a la imagen
COPY . /app

# Actualiza pip a la última versión
RUN pip install --upgrade pip

# Instala las dependencias necesarias especificadas en requirements.txt
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto que usará Flask (por defecto 5000)
EXPOSE 5000

# Define el comando para ejecutar la aplicación
CMD ["flask","run"]