FROM node:18-alpine
ENV VITE_HOST=0.0.0.0
ENV VITE_PORT=5173
ENV VITE_CLIENT_PORT=8000
WORKDIR /app

COPY package.json .

RUN npm install

#RUN npm i -g serve

COPY . .

#RUN npm run build
#RUN npm run dev
#EXPOSE 3000

#CMD [ "serve", "-s", "dist" ]
CMD ["npm", "run", "dev"]
